# Makefile for Project Shell

CC = gcc
CFLAGS = -ansi -Wall -g -O0 -Wwrite-strings -Wshadow -pedantic-errors -fstack-protector-all

PROGS = d8sh

all: $(PROGS)

d8sh: d8sh.o executor.o lexer.o parser.tab.o
  $(CC) -lreadline -o d8sh d8sh.o executor.o lexer.o parser.tab.o

d8sh.o: d8sh.c
	$(CC) $(CFLAGS) -c d8sh.c

executor.o: executor.c executor.h
	$(CC) $(CFLAGS) -c executor.c

lexer.o: lexer.c lexer.h
	$(CC) $(CFLAGS) -c lexer.c

parser.tab.o: parser.tab.c
	$(CC) $(CFLAGS) -c parser.tab.c

clean:
	rm -f *.o $(PROGS) a.out

